name: Release Pipeline

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.MRKSPH_BOT_TOKEN }}
      - name: Set up Git for CI/CD bot
        run: |
          git config --global user.name 'mrksph-bot'
          git config --global user.email 'markscosta96@gmail.com'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Release
        run: mvn -B gitflow:release-start gitflow:release-finish -DreleaseVersion=${{ github.event.inputs.release_version }} -DdevelopmentVersion=${{ github.event.inputs.release_version }}-SNAPSHOT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
